const adminDashboardPage = require('../../../support/pageObjects/LMS-2/AdminDashboardPage')
const adminCalenderHomePage = require('../../../support/pageObjects/LMS-2/AdminCalenderHomePage')
const dayjs = require('dayjs')
describe("Verify admin calender Appointment functionalities - Sprint 21(EL-375,EL-6267,EL-6268)", function () {

    before(function () {
        cy.visit(Cypress.env('urlMain'))
        cy.fixture('LMS/AdminLoginCredentials').then(function (validAdminLoginData) {
            cy.AdminPostSetup(validAdminLoginData.newUsername, validAdminLoginData.password)
        })
    })
    beforeEach(function () {
        cy.viewport(1920, 1080)
        cy.fixture("LMS/adminCalenderAppointment.json").as("appointmentdata")
    })
    it('EL-375/ES375-01 "To validate school admin/teacher is able to create ""Appointments"" by clicking on ""Appointments""option present in the calendar."',function () {
        adminDashboardPage.getCalenderBtn().click({ force: true })
        adminCalenderHomePage.getCreateNewBtn().click()
        adminCalenderHomePage.getAppointmentBtn().click()
        adminCalenderHomePage.getEnterAppointmentTitlefield().should('be.visible').and('be.enabled')
    })
    it('EL-375/ES375-02 To validate the following details are displayed for the create appointment such as Appointment Title,Add Attendees,Date,Start Time,End Time,Remind,Description,Appointment Type,Meeting Link,Location.',function () {
        adminCalenderHomePage.getEnterAppointmentTitlefield().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateApointmentAddPeopleLink().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateApointmentDate().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentStartTime().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentEndTime().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentRemindDropdown().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentAddDescription().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentAppointmentType().scrollIntoView().should('be.visible')
        adminCalenderHomePage.getCreateAppointmentMeetingLink().scrollIntoView().should('be.visible')
    })
    it('EL-375/ES375-03 To validate  user is able to enter only 50 max characters and alphanumeric ,Free text  in Appointment title" field.',function () {
        adminCalenderHomePage.getEnterAppointmentTitlefield().clear().type(this.appointmentdata.Appointment50CharecterAlphanumeric)
    })
    it('EL-375/ES375-05 To validate "Teachers list" of the school is displayed after user clicks on"Teachers" tab.',function () {
        adminCalenderHomePage.getEnterAppointmentTitlefield().clear().type(this.appointmentdata.AppointmentTitle)
        adminCalenderHomePage.getCreateApointmentAddPeopleLink().click()
        adminCalenderHomePage.getCreateApointmentTeacherTab().click()
        adminCalenderHomePage.getCreateAppointmentTeacherSearchField().type(this.appointmentdata.teacher+'{enter}')
        cy.wait(1000)
        adminCalenderHomePage.getCreateAppointmentTeacherCheckbox().should('be.enabled')
    })
    it('EL-375/ES375-09 "To validate user is able to view the total count of attendees added with four profile picture."',function () {
        adminCalenderHomePage.getCreateAppointmentTeacherCheckbox().check()
        adminCalenderHomePage.getCreateAppointmentCloseLink().click()
        adminCalenderHomePage.getCreateAppointmentAttendeesCount().should('be.visible')
    })
    it('EL-375/ES375-10 To validate user can add more people by  clicking on +Add people .',function () {
        adminCalenderHomePage.getCreateApointmentAddPeopleLink().should('be.visible')
    })

    it('EL-6267/ES6267-01 To validate school admin/teacher is able to edit  appointment so that he can mak any changes in the created  appointment .', function () {
        adminCalenderHomePage.getCreateApointmentDate().click()
        adminCalenderHomePage.getCreateApointmentDateselect(dayjs().format("D")).click()
        adminCalenderHomePage.getCreateAppointmentStartTime().click()
        adminCalenderHomePage.getCreateAppointmentStartTimeing().click({ force: true })
        adminCalenderHomePage.getCreateAppointmentStartTimeingAM().click({ force: true })
        adminCalenderHomePage.getCreateAppointmentStartTime().click()
        cy.wait(1000)
        adminCalenderHomePage.getCreateAppointmentEndTime().click()
        adminCalenderHomePage.getCreateAppointmentEndTimeing().click({ force: true })
        adminCalenderHomePage.getCreateAppointmentEndTimeingPM().click({ force: true })
        adminCalenderHomePage.getCreateAppointmentEndTime().click()
        cy.wait(1000)
        adminCalenderHomePage.getCreateAppointmentRemindDropdown().click({ force: true })
        adminCalenderHomePage.getCreateAppointmentRemindDropdownDonotremindOpt().click({ force: true })
        cy.wait(1000)
        adminCalenderHomePage.getCreateAppointmentAddDescription().type(this.appointmentdata.AppointmentDescription)
        adminCalenderHomePage.getCreateAppointmentAppointmentTypeDropdown().click({ force: true })
        cy.wait(1000)
        adminCalenderHomePage.getCreateAppointmentAppointmentType().click()
        adminCalenderHomePage.getCreateAppointmentAppointmentTypeOnlineOpt().click()
        adminCalenderHomePage.getCreateAppointmentMeetingLink().click().type(this.appointmentdata.AppointmentMeetingLink)
        adminCalenderHomePage.getCreateAppointmentSaveAppointmentBtn().click()
        adminCalenderHomePage.getCreateAppointmentXBtn().click()
        adminCalenderHomePage.getAppointmentCheckbox().check()
        adminCalenderHomePage.getAppointmentAutomation().click()
        adminCalenderHomePage.getAppointmentEditAppointmentBtn().should('be.visible')
    })
    it('EL-6267/ES6267-02 "To validate ""Edit"" option is avialable for the teacher ."', function () {
        adminCalenderHomePage.getAppointmentEditAppointmentBtn().click()
        adminCalenderHomePage.getEnterAppointmentTitlefield().should('be.enabled')
    })
    it('EL-6267/ES6267-03 "The following details are displayed by clicking on""Edit Appointment"" such as ""Save Appointment ""and cancel button."', function () {
        adminCalenderHomePage.getAppointmentSaveAppointmentBtn().should('be.visible')
        adminCalenderHomePage.getAppointmentCancelAppointmentBtn().should('be.visible')
    })
    it('EL-6267/ES6267-04 "To validate respective attendees of the appointment  is notified through mail and updated  in the calendar"', function () {
        adminCalenderHomePage.getAppointmentSaveAppointmentBtn().click()
        adminCalenderHomePage.getCreateAppointmentXBtn().click()
        adminCalenderHomePage.getAppointmentAutomation().should('be.visible')
    })
    it('EL-6267/ES6267-05 To validate "successful "pop-up is displayed stating  that "Appointment saved" and user is redirected  your calendar screen if user clicks on save appointment.', function () {
        adminCalenderHomePage.getAppointmentCheckbox().check()
        adminCalenderHomePage.getAppointmentAutomation().click()
        adminCalenderHomePage.getAppointmentEditAppointmentBtn().click()
        adminCalenderHomePage.getAppointmentSaveAppointmentBtn().click()
        cy.contains(this.appointmentdata.appointmentSaveConfermationMessage).should('be.visible')
        adminCalenderHomePage.getCreateAppointmentXBtn().click()
    })
    it('EL-6267/ES6267-06  "To validate no changes are saved and user is redirected your calendar screen if user clicks on""Cancel ""button."', function () {
        adminCalenderHomePage.getAppointmentCheckbox().check()
        adminCalenderHomePage.getAppointmentAutomation().click()
        adminCalenderHomePage.getAppointmentEditAppointmentBtn().click()
        adminCalenderHomePage.getAppointmentCancelAppointmentBtn().click()
    })
    it('EL-6268/ES6268-01 "To validate user is able to delete appointment  by clicking on ""Delete ""option present in the created appointement from  the calendar."', function () {
        adminCalenderHomePage.getAppointmentCheckbox().check()
        adminCalenderHomePage.getAppointmentAutomation().click()
        adminCalenderHomePage.getAppointmentDeleteAppointmentBtn().should('be.visible')
    })
    it('EL-6268/ES6268-02 "To validate ""confirmation ""pop-up is populated stating that ""Are you sure you want to delete the appointment?""  by clicking  on ""Delete ""option."', function () {
        adminCalenderHomePage.getAppointmentDeleteAppointmentBtn().click()
        cy.contains(this.appointmentdata.appiontmentDeleteConfermation).should('be.visible')
    })
    it('EL-6268/ES6268-03 "To validate the following details are displayed in the pop-up  if user clicks on""Delete""option such as ""Delete Appointment"" and ""Cancel ""  button ."', function () {
        adminCalenderHomePage.getDeletePopupDeleteAppointmentBtn().should('be.visible')
        adminCalenderHomePage.getDeletePopupCancelAppointmentBtn().should('be.visible')
    })
    it('EL-6268/ES6268-06 "To validate ""X"" cross button  is aviable in the pop-up screen ."',function () {
        adminCalenderHomePage.getDeletePopupXBtn().should('be.visible')
    })
    it('EL-6268/ES6268-05 To validate "successful "pop-up is displayed stating  that "The Appointment has been deleted " and user is redirected  your calendar screen.', function () {
        adminCalenderHomePage.getDeletePopupDeleteAppointmentBtn().click()
        cy.contains(this.appointmentdata.appointmentDeletedConfermationMessage).should('be.visible')
    })
    it('EL-6268/ES6268-04 "To validate respective attendees of the appointement is notified through mail about the removal of the appointment."',function () {
        adminCalenderHomePage.getAppointmentAutomation().should('not.exist')
    })
   
})